export const BATTLE_BACKGROUND_ASSET_KEYS = Object.freeze({
  FOREST: "FOREST",
});

export const MONSTER_ASSET_KEYS = Object.freeze({
  IGUANIGNITE: "IGUANIGNITE",
  CARNODUSK: "CARNODUSK",
  IGNIVOLT: "IGNIVOLT",
  AQUAVALOR: "AQUAVALOR",
  FROSTSABER: "FROSTSABER",
});

export const BATTLE_ASSET_KEYS = Object.freeze({
  HEALTH_BAR_BACKGROUND: "HEALTH_BAR_BACKGROUND",
  BALL_THUMBNAIL: "BALL_THUMBNAIL",
  DAMAGED_BALL: "DAMAGED_BALL",
  TRAINER_YOUTH_GIRL: "TRAINER_YOUTH_GIRL",
  TRAINER_YOUTH_BOY: "TRAINER_YOUTH_BOY",
});

export const HEALTH_BAR_ASSET_KEYS = Object.freeze({
  LEFT_CAP: "LEFT_CAP",
  MIDDLE: "MIDDLE",
  RIGHT_CAP: "RIGHT_CAP",
  LEFT_CAP_SHADOW: "LEFT_CAP_SHADOW",
  MIDDLE_SHADOW: "MIDDLE_SHADOW",
  RIGHT_CAP_SHADOW: "RIGHT_CAP_SHADOW",
});
